// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imxesrkdgciojihloufi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlteGVzcmtkZ2Npb2ppaGxvdWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTUwOTksImV4cCI6MjA2NzA5MTA5OX0.TUadZdOTfE9BscVpxOFYKbjenjqPfVz0R7i21ebCwQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});